name: Delete old workflow runs
on:
  workflow_dispatch:
    inputs:
      min:
        description: 'The minimum runs to keep for each workflow.'
        required: true
        default: 6

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: AZ-X/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{ github.event.inputs.min }}
          retain_days: 0
